# Dockerfile for webhook-based producer
FROM python:3.9-slim

WORKDIR /app

COPY requirements_wh.txt .
RUN pip install --no-cache-dir -r requirements_wh.txt

COPY producer_wh.py .

# Замените 8000 на порт, который вы используете в uvicorn.run
EXPOSE 8000 

CMD ["python", "producer_wh.py"]
