version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bitrix-network
    depends_on:
      - php

  php:
    image: bitrix24/php-fpm:latest # Вам может потребоваться указать конкретную версию
    volumes:
      - ./www:/var/www/html
    networks:
      - bitrix-network
    depends_on:
      - mysql
      - memcached
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=bitrix
      - DB_USER=bitrix
      - DB_PASSWORD=bitrix

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bitrix-network

  memcached:
    image: memcached:latest
    networks:
      - bitrix-network

volumes:
  mysql-data:

networks:
  bitrix-network:
